import os
from email.mime.image import MIMEImage
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMultiAlternatives, send_mail
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django_rq import job

def send_activation_email(user):
    """
    Sends an account activation email to the given user.

    This function generates a time-sensitive activation token and constructs
    an activation link that the user can use to verify their email address.
    It sends both a plain-text and HTML version of the email and embeds a
    logo image inline for improved presentation.

    Steps performed:
        - Generate uidb64 and token for account activation.
        - Build an activation URL using Django's reverse lookup.
        - Prepare plain-text and HTML email content.
        - Attach an inline logo image via MIME.
        - Send the email using Django's email backend.
    """
    subject = 'Confirm your email'
    from_email = settings.DEFAULT_FROM_EMAIL
    to = [user.email]

   
    uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
    token = default_token_generator.make_token(user)
    activation_link = f"http://localhost:8000{reverse('activate', kwargs={'uidb64': uidb64, 'token': token})}"

    text_content = f'Please activate your account using this token: {token}'

 
    html_content = f"""
    <html>
      <body style="width:1000px; font-family: Helvetica, Arial, sans-serif; color: #333; line-height:1.6;">
        <div style="text-align:center; margin-bottom: 20px;">
          <img src="cid:logo_image" alt="Videoflix Logo" style="width:200px;" />
        </div>
        <h2>Dear {user.email},</h2>
        <p>Thank you for registering with Videoflix. To complete your registration and verify your email address, please click the link below:</p>
        <p style="text-align:start; margin:32px 0;">
          <a href="{activation_link}" 
             style="background-color:#1122D9; color:white; padding:12px 24px; text-decoration:none; border-radius:30px; display:inline-block;">
            Activate Account
          </a>
        </p>
        <p>If you did not create an account with us, please disregard this email.</p>
        <p>Best regards,<br>Your Videoflix Team</p>
      </body>
    </html>
    """


    msg = EmailMultiAlternatives(subject, text_content, from_email, to)
    msg.attach_alternative(html_content, "text/html")

   
    logo_path = os.path.join(settings.BASE_DIR, 'templates/images/logo_icon.png') 
    with open(logo_path, 'rb') as f:
        img = MIMEImage(f.read())
        img.add_header('Content-ID', '<logo_image>')  
        img.add_header('Content-Disposition', 'inline', filename='logo_icon.png')
        msg.attach(img)

    msg.send()

User = get_user_model()


def activate_user(uidb64, token):
    """
    Activates a user account based on a base64-encoded user ID and a
    token generated by Django's default token generator.

    The function decodes the user ID, retrieves the corresponding user,
    validates the provided token, and activates the account if the token
    is valid.

    Steps performed:
        - Decode uidb64 to obtain the user ID.
        - Fetch the user instance from the database.
        - Validate the activation token.
        - Activate and save the user if validation succeeds.

    Returns:
        User: The activated user instance if successful.
        None: If decoding, lookup, or token validation fails.
    """
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
        print("Found user:", user.email)
    except Exception as e:
        print("Decode/Get user failed:", e)
        return None

    print("Token:", token)
    print("Check token:", default_token_generator.check_token(user, token))
    if default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return user
    return None




def send_password_reset_email(user):
    """
    Sends a password reset email to the specified user.

    This function generates a time-sensitive token and a base64-encoded user ID,
    constructs a password reset link, and sends both plain-text and HTML versions
    of the email. The HTML email includes an inline logo image for branding.

    Steps performed:
        - Generate uidb64 and token for password reset.
        - Build a password reset URL pointing to the frontend confirmation page.
        - Prepare plain-text and HTML email content.
        - Attach the logo image inline using MIME.
        - Send the email via Django's email backend.

    Args:
        user (User): The user instance to whom the reset email will be sent.
    """
    uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
    token = default_token_generator.make_token(user)
    
    reset_link = f"http://127.0.0.1:5500/pages/auth/confirm_password.html?uid={uidb64}&token={token}"
    
    subject = "Reset your Videoflix password"
    text_content = f"Please reset your password using the following link: {reset_link}"
    
    # HTML mit CID-Referenz
    html_content = f"""
    <html>
      <body style="width:1000px; font-family: Helvetica, Arial, sans-serif; color: #333;">
        <h2>Hello,</h2>
        <p>We recently received a request to reset your password. If you made this request, please click on the following link:</p>
        <p style="text-align:start; margin:32px 0;">
          <a href="{reset_link}" style="background-color:#1122D9; color:white; padding:12px 24px;
             text-decoration:none; border-radius:30px; display:inline-block;">
            Reset Password
          </a>
        </p>
        <p>Please note that for security reasons, this link is only valid for 24 hours</p>
        <p>If you did not request a password reset, please ignore this mail.</p>
        <p>Best regards,<br> <br>Your Videoflix Team</p>
        <div style="text-align:start; margin-top: 20px;">
          <img src="cid:logo_image" alt="Videoflix Logo" style="width:150px;" />
        </div>

        <img src="./Designvorlage password_reset Videoflix.png" alt="">
      </body>
    </html>
    """
    
    msg = EmailMultiAlternatives(subject, text_content, settings.DEFAULT_FROM_EMAIL, [user.email])
    msg.attach_alternative(html_content, "text/html")
    
    # Pfad zum Logo (PNG empfohlen)
    logo_path = os.path.join(settings.BASE_DIR, 'templates', 'images', 'logo_icon.png')
    
    with open(logo_path, 'rb') as f:
        img = MIMEImage(f.read(), _subtype='png')  # PNG muss hier explizit angegeben werden
        img.add_header('Content-ID', '<logo_image>')  # muss mit cid im HTML übereinstimmen
        img.add_header('Content-Disposition', 'inline', filename='logo_icon.png')
        msg.attach(img)
    
    msg.send()


@job
def send_password_reset_email_task(user_id):
    """
    Background task that sends a password reset email to a user by ID.

    This task retrieves the user from the database using the provided
    `user_id` and calls `send_password_reset_email` to send the email.
    If the user does not exist, the task silently ignores the request.

    Args:
        user_id (int): The primary key of the user to send the password reset email to.
    """

    try:
        user = User.objects.get(pk=user_id)
        send_password_reset_email(user)
    except User.DoesNotExist:
        pass