# Generated by Django 5.2.8 on 2025-11-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_path',
            field=models.FileField(default='videos/dummy.mp4', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
