# Generated by Django 5.2.8 on 2025-11-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_video_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
