# Generated by Django 5.2.8 on 2025-11-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_remove_video_thumbnail_url_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
