# Generated by Django 5.2.8 on 2025-11-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_remove_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(blank=True, null=True),
        ),
    ]
