# Generated by Django 5.2.8 on 2025-11-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0007_remove_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
