# Generated by Django 5.2.8 on 2025-11-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0008_video_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
    ]
