# Generated by Django 5.2.8 on 2025-11-18 20:24

import video_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0009_remove_video_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=video_app.models.Video.thumbnail_upload_path),
        ),
    ]
